#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/trans_tv_db
#    username: root
#    password: ''
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    database: MYSQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  application:
#    name: trans-tv


spring:
  datasource:
    url: jdbc:mysql://y01wtaqxwxcbx9m8:bj4p2plf2wg6dxdm@jfrpocyduwfg38kq.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/neauurdg3e9egqdj
    username: y01wtaqxwxcbx9m8
    password: 'bj4p2plf2wg6dxdm'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: Africa/Nairobi
  application:
    name: trans-tv
