#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/trans_tv_db
#    username: root
#    password: ''
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    database: MYSQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  application:
#    name: trans-tv

spring:
  datasource:
    url: jdbc:mysql://l1zc8re44lur4pg2:kjcd50u76o23mn1a@z8dl7f9kwf2g82re.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/io51g48r9q59h3r2
    username: l1zc8re44lur4pg2
    password: 'kjcd50u76o23mn1a'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: Africa/Nairobi
  application:
    name: trans-tv
